### ISSUE TITLE
Member tools obscures left hand column

### ISSUE THREAD

**Issue by cuberoot** [StrategicDevelopment/FoodCoop#1]
The member tools obscures some of the items in the left side of the screen. For example you cannot delete items because the delete button is obscured

![screen_shot_2015-01-08_at_11_10_39_am](https://cloud.githubusercontent.com/assets/154097/5654356/12ce36bc-9727-11e4-93d3-41fd6d70c38d.png)

**Comment by sean-stanley** [comment]
If you close the member tools bar can you see the rest of the screen?

I believe this overlap is a css issue to try and avoid crushing the content on smaller device width's. I'll see what can be done.

**Comment by cuberoot** [comment]
If you close the member tools you can see the whole thing. When you open the tools, the screen shift right, but not far enough.

Maybe some of your rules need to be in media selectors for small devices?

**Comment by sean-stanley** [comment]
Made CSS changes in latest commit. Closing issue.
